### ISSUE TITLE
make errors out in Postgres 11 stable

### ISSUE THREAD

**Issue by rupendrab** [ibarwick/config_log#2]
The make errors out for Postgres 11 because the signature of BackgroundWorkerInitializeConnection in src/include/postmaster/bgworker.h has changed to add a third parameter.

extern void BackgroundWorkerInitializeConnection(const char *dbname, const char *username, uint32 flags);

Error in compilation below:
`bash-4.4# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -I. -I./ -I/usr/local/include/postgresql/server -I/usr/local/include/postgresql/internal  -D_GNU_SOURCE -I/usr/include/libxml2   -c -o config_log.o config_log.c
config_log.c: In function 'config_log_main':
config_log.c:299:2: error: too few arguments to function 'BackgroundWorkerInitializeConnection'
  BackgroundWorkerInitializeConnection(config_log_database, NULL);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from config_log.c:23:
/usr/local/include/postgresql/server/postmaster/bgworker.h:143:13: note: declared here
 extern void BackgroundWorkerInitializeConnection(const char *dbname, const char *username, uint32 flags);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
config_log.c:308:8: error: too few arguments to function 'WaitLatch'
   rc = WaitLatch(&MyProc->procLatch,
        ^~~~~~~~~
In file included from config_log.c:25:
/usr/local/include/postgresql/server/storage/latch.h:174:12: note: declared here
 extern int WaitLatch(volatile Latch *latch, int wakeEvents, long timeout,
            ^~~~~~~~~
config_log.c: In function '_PG_init':
config_log.c:372:9: error: 'BackgroundWorker' {aka 'struct BackgroundWorker'} has no member named 'bgw_main'; did you mean 'bgw_name'?
  worker.bgw_main = config_log_main;
         ^~~~~~~~
         bgw_name
make: *** [<builtin>: config_log.o] Error 1
`

**Comment by ibarwick** [comment]
Code now updated to handle various changes in recent PostgreSQL versions.
